### PR TITLE
Voice Record Support

### PR DESCRIPTION
**Pull request by BlazenBoi**
## Summary

[ ] Adds Voice Recording Support

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pre-commit run --all-files`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

Problems:

- [x] Static on multiple people talking

### CODE REVIEW

**Comment by BlazenBoi** [comment]
Ok it seems the only Pre-Commit fail is the example I added so idk what to do about that.

**Comment by VincentRPS** [comment]
@BlazenBoi did you fix the static error from the original discord.py pull request?

**Comment by BlazenBoi** [comment]
> @BlazenBoi did you fix the static error from the original discord.py pull request?

I didn't I just copied it over.

**Comment by BlazenBoi** [comment]
I accidentally commited my whole venv but fixed that. so yeah @VincentRPS fixed the static, and I got pre-commit set up.

**Comment by BlazenBoi** [comment]
Ok im struggling with this mp3 thing so I might make a converter in the test bot but the wav files work fine.

**Comment by VincentRPS** [comment]
@BlazenBoi pcm and mp3 only work with ffmpeg btw

**Comment by EQUENOS** [comment]
This implementation of voice receive works but there're still reasons why we can't merge it:
- The implementation is relatively old-styled, because it isn't properly type hinted
- We're using someone else's code here without even asking a permission
This is why we have to close this and implement the feature ourselves, following modern python standards. Thank you for your PR though.

**Pull request closed without merging**
