### PR TITLE
feat: add documentation search hotkeys

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

Adds a few common keyboard shortcuts for focusing the search bar in the documentation:
- `ctrl+k`: algolia/docsearch (hence also used by sites like [discord.dev](https://discord.dev) and [guide.disnake.dev](https://guide.disnake.dev))
- `/`: commonly seen in a few applications; Sphinx 4.5 will [support](https://github.com/sphinx-doc/sphinx/commit/799385f5558a888d1a143bf703d06b66d6717fe4) it, GitLab uses it, algolia/docsearch also appears to support it
- `s`: GitHub + GitLab

preview: https://disnake--434.org.readthedocs.build/en/434/

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by onerandomusername — CHANGES_REQUESTED** [review]
Before making this change, I think we also need to add pressing escape to defocus the search bar. Right now, you can press `s` or `/` to focus it but pressing esc does not defocus it as one would expect.

**Comment by onerandomusername** [comment]
I also don't think we need to add `s` as on github and gitlab they overload most of the keyboard, which we do not do. `/` and `ctrl + k` are more than sufficient

**Comment by shiftinv** [comment]
> Before making this change, I think we also need to add pressing escape to defocus the search bar. Right now, you can press `s` or `/` to focus it but pressing esc does not defocus it as one would expect.

Yeah, sounds like a good idea; added in 729cc22454adbcb149ec6b91f5106c0da5ef6808.

**Comment by onerandomusername** [comment]
I'm not entirely a fan of `s` as this already introduces two other methods, `/` and `ctrl+k`

**Review by onerandomusername — APPROVED** [review]
changed my mind, I'm good with this.

**Pull request merged**
