### PR TITLE
Fully Using orjson

### PR DESCRIPTION
**Pull request by RPSMain**
## Summary

Implement Full Use Of orjson

## Checklist

- [x] If code changes were made then they have been tested
    - [x] I have formatted the code properly by running `black .`

### CODE REVIEW

**Comment by thesadru** [comment]
I'm a bit confused here. What's the point of just importing orjson? Surely some other changes must be made too

**Comment by shiftinv** [comment]
I agree with @thesadru. Just importing `orjson` will do nothing if it's not installed, and break any usages of `json` if it is installed. Instead, `utils._from_json` and `utils._to_json` should be used, which automatically switches to `orjson` if available.

**Comment by shiftinv** [comment]
The `json` import in `http.py` is also unused, so that could actually be removed entirely, afaict.

**Comment by VincentRPS** [comment]
> I'm a bit confused here. What's the point of just importing orjson? Surely some other changes must be made too

shouldn't need to eg: utils
https://github.com/DisnakeDev/disnake/blob/5a89e3a11574920969b110d9ef6b5b0bb738c42a/disnake/utils.py

**Comment by VincentRPS** [comment]
> The `json` import in `http.py` is also unused, so that could actually be removed entirely, afaict.

i think this is why it's imported
https://github.com/DisnakeDev/disnake/blob/a90bc3852f91fcb8e3f1c1a0637f972a8d18c345/disnake/http.py#L108-L117

**Review by onerandomusername — CHANGES_REQUESTED** [review]
This won't work. The orjson module must also be used in place of the json modules.

Anywhere in the used files must also use orjson over json.

One way to do this is set `orjson` to None if it cannot be imported, and guard usage by checking if orjson is not None against it.

Here are some of the changes that would need to be made: https://github.com/ijl/orjson#migrating

Another way to do this would be from imports, and import the needed methods from each library. in addition, writing a dump method that standardizes this output depending on which one is imported would also be useful.

As mentioned in their docs
>>> To migrate from the standard library, the largest difference is that orjson.dumps returns bytes and json.dumps returns a str.

**Comment by onerandomusername** [comment]
> The `json` import in `http.py` is also unused, so that could actually be removed entirely, afaict.

For this, I suggest using flake8-isort and isort itself to find all unused imports on the entire project.

HOWEVER, some of those imports are used by other modules or re-exported as part of the public api so it won't be possible to remove all of them.

**Comment by shiftinv** [comment]
As discussed above, this plainly does not work; just importing one or the other and doing no additional handling won't change anything, that's what `utils._from_json` and `utils._to_json` are for.

Superseded by #184.

**Pull request closed without merging**
