### PR TITLE
typing: update command decorators, fix item typevar bounds

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

- Add generic parameters to user/message command decorators in `InteractionBotBase`, similar to #514
- Update `Param` default parameter type to improve compatibility with callable/dynamic defaults
- Fix view typevar in ui items by using `Optional[View]` bound instead of `View, None` constraints

some changes were originally part of #519, but now split to avoid additional scope creep

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by onerandomusername** [comment]
Blocked by #559

**Review by onerandomusername — CHANGES_REQUESTED** [review]
docs are failing due to incorrect references

**Comment by shiftinv** [comment]
> docs are failing due to incorrect references

fixed

**Review by onerandomusername — APPROVED** [review]
looks good

**Pull request merged**
