### PR TITLE
addes new object info

### PR DESCRIPTION
**Pull request by JDJGInc**
## Checklist

- [x] If code changes were made then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `black .`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by JDJGInc** [comment]
image

**Comment by JDJGInc** [comment]
image
tested it too

**Comment by JDJGInc** [comment]
from disnake.ext import commands
import disnake
import typing
from disnake.ext.commands.core import command

bot = commands.Bot(command_prefix = "e*", intents=disnake.Intents.all())


@bot.event
async def on_ready():
    print(f"Bot is ready")

@bot.command(brief="gives information on snowflakes")
async def snowflake_info(ctx, *, snowflake: typing.Optional[disnake.Object] = None):

    if not snowflake:
      await ctx.send("you either returned nothing or an invalid snowflake now going to the current time for information.")

    generated_time = await commands.ObjectConverter().convert(ctx, argument=f"{int((disnake.utils.utcnow()).timestamp() * 1000 - 1420070400000) << 22 | 0x3fffff}")
    #yes the later bit uses generate_snowflake's older version

    snowflake = snowflake or generated_time

    embed = disnake.Embed(title="❄️ SnowFlake Info:", color=5793266)

    embed.add_field(name="Created At:",
                    value=f"{disnakeutils.format_dt(snowflake.created_at, style = 'd')}\n{disnake.utils.format_dt(snowflake.created_at, style = 'T')}")

    embed.add_field(name="Worker ID:",
                    value=f"{snowflake.worker_id}")

    embed.add_field(name="Process ID:",
                    value=f"{snowflake.process_id}")

    embed.add_field(name="Increment:", value=f"{snowflake.increment_id}")

    embed.set_footer(text=f"Snowflake ID: {snowflake.id}")

    await ctx.send(embed=embed)

TOKEN = ""
bot.run(TOKEN)

**Comment by thesadru** [comment]
Closing as the quality of this pr is unmanageable.

**Pull request closed without merging**
