### PR TITLE
fix(misc): ignore `lib/` created by virtualenv

### PR DESCRIPTION
**Pull request by ItsAleph**
## Summary

virtualenv creates `lib/` folder, which [is not ignored by Git](https://github.com/DisnakeDev/disnake/pull/722/commits/bcd4f5926f072d4b0518ea29c667dbc9b12aee38) yet it's not included in MANIFEST.in, [making check-manifest complain](https://github.com/DisnakeDev/disnake/runs/8081816019?check_suite_focus=true). This PR updates .gitignore to ignore `lib/` folder, too.

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by EQUENOS — APPROVED** [review]

**Comment by shiftinv** [comment]
The virtualenv folder name is determined by whatever you pass when creating it - `virtualenv venv` creates a `venv/` folder with e.g. `venv/lib/python3.10/site-packages`.
The common virtualenv names `venv` and `.venv` are already .gitignore'd, not sure how the `lib/` directory would appear in the repo root (unless you ran `virtualenv .`, I suppose?).

Anyway, seems fine to me, though this change doesn't need a changelog entry since it's not relevant to end users.

**Comment by ItsAleph** [comment]
I usually make virtual envs like this
```sh
git clone https://github.com/someorg/repo
virtualenv repo
```
(i.e., like you said, `virtualenv .`).
Even though this might not be a very popular place to create venvs, having a former `except:` for such cases will not make everything worse.

About changelog entry.. IIRC github won't let you merge the pr if any of the required checks dont pass.. I'll remove changelog entry, but how can we ignore that check?

**Comment by toolifelesstocode** [comment]
It wouldn't be best to be stacking things onto a PR, but is there any chance `__pycache__` could be git ignored? At some point, a pycache folder was created(however I'm not too sure what I did to make that happen), so it would be nice if that could be gone too.

**Comment by ItsAleph** [comment]
Why not, i think (but i'll better wait for shift's or other maintainer opinion)

**Comment by shiftinv** [comment]
> It wouldn't be best to be stacking things onto a PR, but is there any chance `__pycache__` could be git ignored? At some point, a pycache folder was created(however I'm not too sure what I did to make that happen), so it would be nice if that could be gone too.

`__pycache__` directories themselves aren't ignored, and while that could be changed, it's not necessary as they should only contain `*.pyc` files. Those *are* already ignored, and git doesn't care about empty directories :p

**Comment by ItsAleph** [comment]
changelog entry removed

**Comment by toolifelesstocode** [comment]
> > It wouldn't be best to be stacking things onto a PR, but is there any chance `__pycache__` could be git ignored? At some point, a pycache folder was created(however I'm not too sure what I did to make that happen), so it would be nice if that could be gone too.
> 
> `__pycache__` directories themselves aren't ignored, and while that could be changed, it's not necessary as they should only contain `*.pyc` files. Those _are_ already ignored, and git doesn't care about empty directories :p

Ahh okay, I see the logic now.

**Review by toolifelesstocode — APPROVED** [review]

**Comment by onerandomusername** [comment]
This isn't necessary, as you can use a `.git/info/exclude` file for adding user-specific ignores. What we've added to the `.gitignore` file are build artifacts that may be appearing for everyone, or files that most people will be using.

**Pull request closed without merging**
