### PR TITLE
refactor(lint): use absolute imports

### PR DESCRIPTION
**Pull request by onerandomusername**
## Summary

Use absolute imports. 

This is just to see if we like the change and want to implement it.

## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by shiftinv** [comment]
Is there any runtime impact (re cyclic imports and such)?

I'm a bit ambivalent about this, but it seems like fine overall.
It improves readability a bit, and while relative imports aren't fully discouraged anymore, PEP 8 recommends absolute imports in most cases.

My main gripe is the fact that it currently only includes parents, which results in sibling imports being separated visually:
image
It's configurable through `flake8-tidy-imports.ban-relative-imports`, can't tell if that's a good idea though.

**Comment by onerandomusername** [comment]
There seems to be some issues with ruff and autofixing relative imports in namespaced packages. I'll be looking more into this.

**Comment by onerandomusername** [comment]
Reported bug here. https://github.com/charliermarsh/ruff/issues/3318

A temporary workaround to get correct imports is to create `disnake/ext/__init__.py` and then run ruff

**Comment by shiftinv** [comment]
> Reported bug here.

Now that ruff v.254 is out, what's the state of this PR?

**Comment by onerandomusername** [comment]
> > Reported bug here.
> 
> Now that ruff v.254 is out, what's the state of this PR?

Finally updated the imports in [`7537568` (#951)](https://github.com/DisnakeDev/disnake/pull/951/commits/7537568d6cc16be4bb6e06439f0f87cb889391ac)

As stated before, I'm still unsure if we want to move forward with this, but on the other hand, there's no runtime loss.

**Comment by shiftinv** [comment]
I've contemplated this change some more; going to vote "no" on this, but if others would prefer this change to be merged, then fine by me.

Most of these issues are minor, but I'm also not really seeing any advantages here, so it's still a net negative overall:
- This will result in a bunch of merge conflicts. Sure, not a huge deal, but still... annoying and frankly unnecessary
- It makes imports in deeply nested packages quite verbose; I don't see a reason to replace `.cooldowns` with `disnake.ext.commands.cooldowns` if we're already inside `disnake.ext.commands.something`
- In `disnake.ext.*`, imports from the main lib and ext previously were visually separated (by virtue of using absolute imports for the former); the new order is confusing:
  image

**Comment by onerandomusername** [comment]
Agreed. This may be worth it with a different configuration at some later point in time.

**Pull request closed without merging**
