### PR TITLE
Docs header/sidebar/layout cleanup

### PR DESCRIPTION
**Pull request by bast0006**
## Summary

This pull request reworks the general styling layout for the generated documentation to be more in line with it's intended use (IE: it is designed for desktop primarily, with an alternate view for mobile, instead of a mobile view that is altered for desktop.) It also converts a fixed-width horizontal-view layout into a flow-width with a popout for navigation on smaller screen sizes, which solves the issue of smaller or shrunken doc views requiring horizontal scroll as well as a layout issue with the old styles that made the docs unusable on certain intermediate screen sizes. The headers are smaller, and sticky so that documentation search is available without jumping to the top.

It should hopefully: 
* read easier
* function better and more smoothly
* have interface elements closer to where they would be expected to be
* not lose any prior functionality, except where by design ( the serif option, as well as manual override of dark/light themes have been intentionally removed. Dark/light theming now behaves solely according to browser instruction. )

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint` or `pre-commit run --all-files`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by EQUENOS** [comment]
I wish I could properly review this one...
Well, I scrolled through the docs and it looks great, that's all I can say. There's one thing that's kind of uncomfortable - when I hover over any link that is close to the edge of the screen, the preview goes outside of the frame. It's not related to this particular PR though.

**Review by abhigyantrips — APPROVED** [review]
LGTM. Respect the time you guys put into this. 🙌🏽

**Review by onerandomusername — CHANGES_REQUESTED** [review]
LGTM, quite fond of these changes. 


I will approve later, when #275 is ready to go as well. I want the documentation changes to both be merged at once so we have both a content and theme refresh at once 😄

**Review by shiftinv — APPROVED** [review]
Looked through the changes and the preview, looks great! Thanks for putting in all that effort :)

**Pull request merged**
