### PR TITLE
fix(voice): send speaking packet on reconnect

### LINKED ISSUE #845: bug: `VoiceClient.is_playing()` continue to be `True` even when the audio stops
### Summary

A playing `VoiceClient` that gets moved in another `VoiceChannel` appear to stops reproducing the audio, though `VoiceClient.is_playing()` is `True`

### Reproduction Steps

Join a `VoiceChannel` and repoduce something
Move the bot into another `VoiceChannel`
Even if the bot doesn't reproduce any audio, `VoiceClient.is_playing()` continue to be `True`

### Minimal Reproducible Code

```python
@bot.slash_command()
async def test(inter):
    channel: disnake.VoiceChannel = await bot.fetch_channel(874005538285977603)
    vc = await channel.connect()
    vc.play(disnake.FFmpegPCMAudio("https://github.com/ninjamuffin99/Funkin/blob/a083938ac803a91fbb15f03e432dea620f8a3b4a/assets/songs/bopeebo/Inst.mp3?raw=true", executable="executable path"))
    while vc.is_playing():
        print(vc.is_playing())
        await asyncio.sleep(2)
```

### Expected Results

`VoiceClient.is_playing()` should be `False` also if possible it would be great if the audio reproduction could resume when the bot is moved in another `VoiceChannel`

### Actual Results

`VoiceClient.is_playing()` is `True`

### Intents

Irrelevants

### System Information

```markdown
Irrelevant but:

Python v3.9.9
Disnake v2.5.2
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This bug was found thanks to **Rapptz/discord.py#8483** any additional information can be found there

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

`AudioPlayer` would previously not update the [`SPEAKING`](https://discord.com/developers/docs/topics/voice-connections#speaking) state to a non-zero value after reconnecting (which happens when moving between channels, for instance). This results in the bot continuing to send audio packets, which aren't processed by Discord as the speaking state would still be `0`.

Fixes #845.

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by BaronXOfficial** [comment]
Tested locally, unfortunately still ran into an unrecoverable 1006 with the following state:

image

The caught exception, 1006 which per the timestamps occurred as the bot stopped functioning, 

image

**Comment by shiftinv** [comment]
Close code 1006 unfortunately doesn't provide much information, it's an error by the local websocket implementation and just means the connection was closed abnormally. :/
This could be anything from blocking code interfering with connections to miscellaneous network issues, though it should always try to reconnect automatically (also indicated by log messages, which might be helpful in debugging).

**Review by onerandomusername — CHANGES_REQUESTED** [review]
Works, but I noticed one thing about the implementation which I'm not sure we can fix/needs to be fixed.

It looks like right after we connect to a voice channel we send a packet indicating we are not speaking, followed immediately by a speaking packet. 
image

**Comment by shiftinv** [comment]
> It looks like right after we connect to a voice channel we send a packet indicating we are not speaking, followed immediately by a speaking packet.

While it may seem odd, that's intended - clients are required to send at least one op5 packet to set the SSRC, the second one is when it actually starts sending audio data.

**Review by onerandomusername — APPROVED** [review]
lgtm then

**Pull request merged**
