### PR TITLE
Update disable_view.py

### PR DESCRIPTION
**Pull request by CalebEevee**
This pull request fixes `inter.response.edit_message` rather than `self.message.edit`. 
> This error causes an example in one of the example files to not work.

## Checklist

- [x] If code changes were made then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `black .`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by Victorsitou — APPROVED** [review]
Thanks for this 😁

**Comment by shiftinv** [comment]
`on_timeout` should keep using `self.message.edit`, since it doesn't get triggered based on an interaction (hence `inter` doesn't work there)

**Comment by CalebEevee** [comment]
> `on_timeout` should keep using `self.message.edit`, since it doesn't get triggered based on an interaction (hence `inter` doesn't work there)

Alright thanks!

**Comment by shiftinv** [comment]
Nice, thanks!

**Pull request merged**
