### PR TITLE
feat(activity): add undocumented fields

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

Adds the activity fields `id` and `platform`, in addition to the already existing `sync_id` and `session_id`, all of which are not part of the api docs (see https://github.com/discord/discord-api-docs/pull/2219/commits/5822b0bc97fa8ad1f9e87d0426a309cbf680c5d3).
This PR adds the missing fields *without documentation* (hence the skip news label), such that they're still available as they're useful regardless; no guarantees are made regarding their types or presence/absence.

Depends on #685.

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by searchify7** [comment]
What does those fields do?

**Comment by searchify7** [comment]
Oh well fixed typo lol

**Comment by onerandomusername** [comment]
@shiftinv could you rebase this pr on master?

**Comment by shiftinv** [comment]
> @shiftinv could you rebase this pr on master?

Done.

**Review by onerandomusername — APPROVED** [review]
lgtm

**Pull request merged**
