### PR TITLE
docs: update required permissions for prune

### PR DESCRIPTION
**Pull request by vcokltfre**
## Summary

Update the documentation to reflect https://github.com/discord/discord-api-docs/pull/6685

This is a single-word docs-only change, no code has been updated, so testing/etc have been skipped.

### CODE REVIEW

**Comment by vcokltfre** [comment]
Draft as the docs change isn't solidified yet, but when it is this can be merged.

**Comment by mezotv** [comment]
Discord just reverted this after the commit :kekw:

**Comment by mezotv** [comment]
Purge would then require the `MANAGE_GUILD` and `KICK_MEMBERS` permissions. Might be good to include both ig?

**Comment by shiftinv** [comment]
this one should be ready to go now, I believe?

**Comment by mezotv** [comment]
> this one should be ready to go now, I believe?

Yep, should be ready to be merged now!

**Comment by Victorsitou** [comment]
Perhaps it would also be a good idea to update the documentation of `Guild.estimate_pruned_members` and add the required permissions to use it

**Comment by shiftinv** [comment]
> Perhaps it would also be a good idea to update the documentation of `Guild.estimate_pruned_members` and add the required permissions to use it

It links to `prune_members` already, so this should be fine to leave as-is for now

**Review by Victorsitou — APPROVED** [review]

**Pull request merged**
