### PR TITLE
Adding Support For Newer Aiohttp Versions

### PR DESCRIPTION
**Pull request by VincentRPS**
## Summary

Bumps aiohttp to the [newest version](https://pypi.org/project/aiohttp/3.8.1/)

### Checklist

- [x] This Changes Requirements

### CODE REVIEW

**Comment by shiftinv** [comment]
The current version range is equivalent to `==3.7.*`; this change would include `3.8.0`, which hasn't been tested for compatibility yet.

**Comment by Victorsitou** [comment]
Which is the benefit of doing this bump? Do we have issues with that? Will it have better performance?

**Comment by RPSMain** [comment]
> Which is the benefit of doing this bump? Do we have issues with that? Will it have better performance?

Bug fixes
https://github.com/aio-libs/aiohttp/releases/tag/v3.8.1

**Comment by Victorsitou** [comment]
> > Which is the benefit of doing this bump? Do we have issues with that? Will it have better performance?
> 
> Bug fixes https://github.com/aio-libs/aiohttp/releases/tag/v3.8.1

I see, but as far as I know, no one has had issues with aiohttp recently, so I don't see the benefit of doing this bump.

**Comment by RPSMain** [comment]
> > > Which is the benefit of doing this bump? Do we have issues with that? Will it have better performance?
> > 
> > 
> > Bug fixes https://github.com/aio-libs/aiohttp/releases/tag/v3.8.1
> 
> I see, but as far as I know, no one has had issues with aiohttp recently, so I don't see the benefit of doing this bump.

a benefit is pip not uninstalling the new version to install a [different one](https://cdn.upload.systems/uploads/qJCpHUAm.png)

**Comment by Victorsitou** [comment]
> > > > Which is the benefit of doing this bump? Do we have issues with that? Will it have better performance?
> > > 
> > > 
> > > Bug fixes https://github.com/aio-libs/aiohttp/releases/tag/v3.8.1
> > 
> > 
> > I see, but as far as I know, no one has had issues with aiohttp recently, so I don't see the benefit of doing this bump.
> 
> a benefit is pip not uninstalling the new version to install a [different one](https://cdn.upload.systems/uploads/qJCpHUAm.png)

Hmm, I see, makes sense. shiftinv, any thoughts?

**Comment by shiftinv** [comment]
> Bug fixes https://github.com/aio-libs/aiohttp/releases/tag/v3.8.1

The version update in this PR would only include 3.8.0, not 3.8.1 or any newer versions. If we update the requirements, it should be `<3.9.0`, not `<3.8.1`.

> a benefit is pip not uninstalling the new version to install a different one

You should be using virtualenvs anyway, not globally installed packages, to avoid version conflicts like these.

**Comment by jgayfer** [comment]
3.8 has been out for less than a month, I vote we kick this can down the road a bit as it's critical we have a stable version of `aiohttp`.

**Comment by RPSMain** [comment]
> 3.8 has been out for less than a month, I vote we kick this can down the road a bit as it's critical we have a stable version of `aiohttp`.

3.8.1 is not a big change in anyway is can't be since they have to follow SemVer

**Comment by onerandomusername** [comment]
IMHO, this library should be checked for compatibility, and the requirements loosened--if a user has a problem with aiohttp3.8 they can install 3.7, that doesn't change. What changes is that pip won't uninstall 3.8 to install 3.7 since that's what is stated to be compatible.

Waiting until a 3.8.1 of aiohttp doesn't make sense... certain programs can define their own constraints for aiohttp depending on what they need. 

The position of disnake is to ensure its packages function properly and are compatible, if they have bugs then a release blocking that specific version can be done. Disnake is not the end product, the bots built on disnake are, so they should have the freedom they want to use any compatible aiohttp version.

**Comment by jgayfer** [comment]
I agree we should bump up to 3.8 at some point. I simply want to give 3.8 some time to mature, as it's very fresh.

**Comment by RPSMain** [comment]
3.8 should be stable now, it's been very tested.

**Comment by VincentRPS** [comment]
@jgayfer as to aiohttp’s semver notice 3.x.x won’t get any breaking changes, only deprecation only major versions like 4.0 would actually remove stuff and need testing

**Review by jgayfer — APPROVED** [review]
I'm okay to bump to 3.8, as it's been a month now 👍

**Comment by onerandomusername** [comment]
I'd like to see this for 2.3, @shiftinv is that possible?

**Review by shiftinv — APPROVED** [review]

**Review by thesadru — APPROVED** [review]

**Review by onerandomusername — APPROVED** [review]
lets get this merged 🥺

**Pull request merged**
