### PR TITLE
add more pre-commit hooks

### PR DESCRIPTION
**Pull request by onerandomusername**
## Summary

Add pre-commit hooks for trailing whitespace, valid toml and yaml files (may be removed)
single new line at end of files, and consistent file endings.

## Checklist

- [x] If code changes were made, then they have been tested
  - [ ] I have updated the documentation to reflect the changes
  - [x] I have formatted the code properly by running `pre-commit run --all-files`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by shiftinv** [comment]
Looks good, just two things:

- the `name` of the other hooks should be adapted now that most hooks use the infinitive (`check`/`fix` vs. `Running`)
- do we want to add `no-commit-to-branch` with `--branch, stable, --branch, master`? Seems like a sensible choice considering branch protection rules would probably (not sure how that works for org admins) prevent pushes anyway

**Comment by Victorsitou** [comment]
I'm all for using `trailing-whitespace`, but I don't think checking toml and yaml is a good idea, unless we're going to use those files in the future, but for now I don't see why to use those hooks.

**Comment by onerandomusername** [comment]
> I'm all for using `trailing-whitespace`, but I don't think checking toml and yaml is a good idea, unless we're going to use those files in the future, but for now I don't see why to use those hooks.

We actually have a toml and a few yaml files in the repo already. pyproject.toml, pre-commit-config.yaml, .github/workflows/*

**Comment by Victorsitou** [comment]
I know, but those aren't going to be changed in a long time.

**Comment by onerandomusername** [comment]
> I know, but those aren't going to be changed for a long time.

They don't run if no files match. Files will only match if --all-files is provided or they're edited, so I don't see this being a problem.

**Review by shiftinv — APPROVED** [review]

**Pull request merged**
