### PR TITLE
chore: replaced `inspect.iscoroutinefunction` with `asyncio.iscoroutinefunction`

### PR DESCRIPTION
**Pull request by Chromosomologist**
## Summary

Replaced all occurrences of `inspect.iscoroutinefunction` with the slightly more truthy `asyncio.iscoroutinefunction`.
## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by tooruu** [comment]
🗿

**Review by tooruu — APPROVED** [review]
Very chad move. I Approve. 🗿

**Review by shiftinv — APPROVED** [review]
incredibly cool
lgtm

**Review by onerandomusername — APPROVED** [review]
lgtm

**Pull request merged**
