### PR TITLE
docs: split changelog to current and legacy versions

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

Removes `.. versionadded:: 1.x` and `.. versionchanged:: 1.x` directives from the documentation, and unlinks the v1.0 migration page from the main index (keeping the only reference in the changelog), since there technically hasn't been a non-2.x release.
This lowers the element count ever so slightly on the api reference page, and should overall make the documentation a bit less cluttered.

## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by toolifelesstocode — APPROVED** [review]
I've scanned through some other files to make sure that no files are missed, however I can't review this PR's files due to my GitHub constantly crashing 😂, however, it looks good to me so far.

**Comment by onerandomusername** [comment]
I'm not entirely sure this change is worth it. Why should we make this change? (Additionally, this isn't the full scope of changes we should make if we are making this change).

**Comment by shiftinv** [comment]
> I'm not entirely sure this change is worth it. Why should we make this change?

Because of this:
>> there technically hasn't been a non-2.x release

I especially noticed these while working on #695, I don't necessarily see the point in keeping them around, as they provide no information to readers.

<br>

> (Additionally, this isn't the full scope of changes we should make if we are making this change).

Mind elaborating? Not quite sure what you mean.

**Comment by onerandomusername** [comment]
It would make some sense to do one of the following: seperate all changelog entries below 2.x to a new page or add a header saying these are shown for historic or legacy purposes.

Additionally, migrating to 1.0 and migrating to async pages could be removed/have the same header.

**Comment by shiftinv** [comment]
@onerandomusername I've moved the legacy changelogs to a separate page, and linked that at the bottom of the main changelog page.
The two migration pages are linked in the v0.10.0 and v1.0.0 changelog entries, so those can't really be removed without also removing those changelogs. Since they're now only linked on the legacy changelog page, it should be fine to keep em.

**Comment by onerandomusername** [comment]
This indirectly closes or changes #347

**Comment by onerandomusername** [comment]
@shiftinv would you please resolve conflicts?

**Comment by onerandomusername** [comment]
I'm not entirely sure this is a great idea, but I also don' really have a concrete reason why this would be a bad idea either. If anyone has any objections against this pr, or agrees with this pr, please comment react to this pr so we know what others think.

**Comment by onerandomusername** [comment]
@shiftinv would you please resolve conflicts before they grow?

**Comment by onerandomusername** [comment]
I'm still on the fence about removing all 1.x and 0.x references from the documentation. 

However, moving the changelog would be nice, and it would be appreciated if we could implement that. Could you revert the versionchanged 1.x changes from this pr so we can get it merged?

**Comment by shiftinv** [comment]
> However, moving the changelog would be nice, and it would be appreciated if we could implement that. Could you revert the versionchanged 1.x changes from this pr so we can get it merged?

Done.

**Review by onerandomusername — APPROVED** [review]
lgtm

**Pull request merged**
