### PR TITLE
fix: fix errors when trying to deserialize stickers with unknown formats

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

The current sticker deserialization code doesn't account for unknown `format_type`s, potentially resulting in `KeyError`s when trying to parse stickers due to the file extension lookup.
The new .gif sticker format (see #910) is one such format, meaning messages sent with such a sticker will result in exceptions.
This won't result in full crashes in >=2.6, but will still prevent messages with such stickers from being handled.

Instead of computing the url at initialization, it is now essentially deferring the `KeyError` to whenever a bot tries to access `.url`; one potential future change would be to make `url` optional to account for unknown formats.

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Skelmis** [comment]
Would it not be better to take the latter approach of an explicit error when sometime can't be handled (when trying to access it in the property) rather than silently modifying to be incorrect.

With an error as an end disnake user id be well aware it's an issue and to expect that, but having it simply modify the url to now be incorrect I'd be continuing to use the data while expecting it to be valid when it's not

**Comment by shiftinv** [comment]
> With an error as an end disnake user id be well aware it's an issue and to expect that, but having it simply modify the url to now be incorrect I'd be continuing to use the data while expecting it to be valid when it's not

Yeah, I had the exact same thought, tbqh - it would definitely be the *correct* solution, to say the least.
From what I've seen, other client libraries consider anything that's not a lottie sticker to have a `.png` extension, though I'm sure that'll change soon enough.

The best solution would probably be to return `Optional[str]`, however that's also sort of the most breaking one.
I'll go with the `@property` approach for now, but making the url optional may still be worth consideration.

**Comment by Skelmis** [comment]
Could it also be a consideration to introduce a new error for parsing failures? That way end developers could explicitly catch unsupported media types

**Comment by shiftinv** [comment]
> Could it also be a consideration to introduce a new error for parsing failures? That way end developers could explicitly catch unsupported media types

Would be a pretty significant undertaking, mainly since parsing doesn't necessarily happen at one specific time, but also e.g. in some computed properties; also not sure about the possible performance hit.
With the high level of abstraction in the library I'm not sure how viable it is, perhaps something that could be done when(/if) data models get overhauled.

**Pull request merged**
