### PR TITLE
docs: restructure examples and don't hardcode tokens

### PR DESCRIPTION
**Pull request by onerandomusername**
## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by onerandomusername** [comment]
Related PR: #557

**Comment by onerandomusername** [comment]
While more changes could be made to the examples, this is a good start, and I think its worth being added at this condition rather than the ideally finished one--this is still better than what we had.

**Review by toolifelesstocode — CHANGES_REQUESTED** [review]
Looks good to me however, in order to get variables from a .env file, you would need to call [dotenv](https://pypi.org/project/python-dotenv)`.load_dotenv` in order for this to work, otherwise, it returns None. That is, unless there's some workaround that I maybe don't know about :^)

**Comment by onerandomusername** [comment]
Loading the env is done in `__init__.py` if the dotenv module is installed

**Comment by toolifelesstocode** [comment]
> ~Loading the env is done in `__init__.py` if the dotenv module is installed~
> 
> No idea what this comment was initially about, I think I confused it for #247
> 
> To run with dotenv, we can actually use `dotenv run python example_name.py` on the command line which will load all of the environment variables before running the process.

Ah. In that case, LGTM. Apologies for the late response, GitHub notifications are failing me.

**Review by toolifelesstocode — APPROVED** [review]

**Review by shiftinv — APPROVED** [review]
Looks good to me!
I've decided to not do any detailed content changes here, reverting some of my previous commits; that's something for another PR, to keep things organized.

@onerandomusername Does this need a changelog entry, and if so, could you add one?

**Comment by onerandomusername** [comment]
not newsworthy on its own, at least not right now

**Pull request merged**
