### PR TITLE
Add Generation for Documentation Download

### PR DESCRIPTION
**Pull request by davids-tips**
## Summary

It adds the ability to download the documentation for offline use.
## Checklist

~-  If code changes were made, then they have been tested~
~-  I have updated the documentation to reflect the changes~
~-  I have formatted the code properly by running `task lint`~
~-  I have type-checked the code by running `task pyright`~
~-  This PR fixes an issue~
~-  This PR adds something new (e.g. new method or parameters)~
~-  This PR is a breaking change (e.g. methods or parameters removed/renamed)~
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by davids-tips** [comment]
Going to fix the error with readthedocs

**Comment by davids-tips** [comment]
And I am now awaiting approval from an admin.

**Comment by shiftinv** [comment]
PDF builds are unfortunately broken in a couple ways due to the custom builders being used, not to mention building PDFs is rather slow, and I don't really see the benefit of epub builds since the formatting doesn't quite work there.
Building htmlzip would be an option, though it adds about 40% extra build time ([html](https://readthedocs.org/projects/disnake-test-1/builds/17026076/) vs [html+htmlzip](https://readthedocs.org/projects/disnake-test-1/builds/17026095/)) - really not sure if that's worth it, so I'll wait for the opinions of others on that.

**Comment by davids-tips** [comment]
@shiftinv as you can see I removed pdf and epub. What would you reccomend as the htmlzip. Should it just be html?

**Comment by davids-tips** [comment]
@shiftinv as you can see I removed pdf and epub. What would you reccomend as the htmlzip. Should it just be html? Also what Is up with the precommit fail?

**Comment by shiftinv** [comment]
> @shiftinv as you can see I removed pdf and epub. What would you reccomend as the htmlzip. Should it just be html?

htmlzip seems fine

> Also what Is up with the precommit check failing?

Looks like it's just extra whitespace, it's a bit difficult to tell in the logs:
image

**Comment by davids-tips** [comment]
I have removed extra whitespace and ensured that all updates are compatible with ReadtheDocs
Code check badge: [lint](https://github.com/DisnakeDev/disnake/actions/workflows/lint.yml)

**Review by shiftinv — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
