### PR TITLE
feat(permissions): add `SET_VOICE_CHANNEL_STATUS` permission

### PR DESCRIPTION
**Pull request by MCausc78**
## Summary

https://github.com/discord/discord-api-docs/pull/6398

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pdm lint`
    - [x] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by EQUENOS — APPROVED** [review]
Lgtm

**Review by spifory — CHANGES_REQUESTED** [review]
Could this pull request just add one of the permissions, either `set_voice_channel_status` or `use_clyde_ai`, just to avoid scope creep

**Comment by EQUENOS** [comment]
> Could this pull request just add one of the permissions, either `set_voice_channel_status` or `use_clyde_ai`, just to avoid scope creep

Both `set_voice_channel_status` and `use_clyde_ai` are permission flags, I don't mind them being in one PR

**Comment by shiftinv** [comment]
This was split from #1090 since there are two separate api docs PRs, which won't necessarily be merged at the same time ~~(if they ever get merged :>)~~. For now, this is fine, but if only one of them eventually gets merged, this PR will have to be cleanly separated from the other one.

**Pull request closed without merging**
