### PR TITLE
Add use Korean to slash_command()

### PR DESCRIPTION
**Pull request by happy-jin1234**
## Summary

Fixed an issue where the Korean slash_command name is supported in Discord but not in this module.

## Checklist

- [ ] If code changes were made then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `black .`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by vcokltfre** [comment]
That regex should in fact be `^[\w-]{1,32}$` to be in line with Discord's API docs. If we do it this way then we end up with a huge amount of characters and scripts in that regex and it becomes unreadable and less efficient.

**Comment by vcokltfre** [comment]
see [Application Command Naming](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-naming)

**Comment by thesadru** [comment]
We shouldn't handle the characters of any specific language but getting rid of the `islower` check is a good idea

What about
```py
assert re.fullmatch(r"[\w-]{1,32}", name) and not name.isupper(), "..."
```

**Comment by EQUENOS** [comment]
Are you sure that Korean slash command names are supported? Looks like they're not (according to [Application Command Naming](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-naming))

**Comment by happy-jin1234** [comment]
> Are you sure that Korean slash command names are supported? Looks like they're not (according to [Application Command Naming](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-naming))

image
image

It seems supported

**Comment by thesadru** [comment]
They must be supported. Localization wouldn't be possible if they weren't.

**Review by thesadru — APPROVED** [review]

**Pull request merged**
