### PR TITLE
feat: application subscriptions

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

https://github.com/discord/discord-api-docs/commit/b97fad33bf2ff7633df32c1a8a206b53aa9fe568 (+ https://github.com/discord/discord-api-docs/commit/b8feadd75e782537545c715fbd71ab4048132363)

~~Since this feature is US-only, I'm unable to test most of it; still working on that part.
Nevertheless, all documented functionality is implemented. The `SKU`/`Entitlement` models have been tested using the example structs provided by the docs, but that's really it.~~  Tested all implemented functionality now.

There are a few `TODO`s scattered across the code regarding testing and naming some things; feedback for those would be appreciated. The api docs are lacking in a few aspects (gateway events, in particular, are somewhat of a guessing game), but most of it is fairly straightforward.

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pdm lint`
    - [x] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Skelmis** [comment]
Would you be able to provide/add an example to this pull request show casing how an end user would be able to utilize this functionality to mark a slash command as requiring premium?

**Comment by shiftinv** [comment]
> Would you be able to provide/add an example to this pull request show casing how an end user would be able to utilize this functionality to mark a slash command as requiring premium? I can see it being quite a regular thing coming up in the future so the clarity would be nice

good point, thanks! Added in https://github.com/DisnakeDev/disnake/pull/1113/commits/989327acb4bc4c9b230f97698d8bc9f430573360.
You don't preemptively mark certain commands as premium-only - it's a separate response type like e.g. `.send_message` or `.defer`. Ultimately it comes down to checking `inter.entitlements` and using `response.require_premium()` where needed.

**Comment by shiftinv** [comment]
Removed the SKU/entitlement HTTP endpoints in 4b66b523ddcd43cefc95093eb8cdaffa6a7603e9 due to https://github.com/discord/discord-api-docs/pull/6502/files#diff-39e6aeaafba5726f3fb409da21a6953dfb679480f09038a0d05f4dd93e89e074R11 :/
Hoping replacements will be available sooner rather than later, but I want to avoid changing this entire PR back to a draft; `Interaction.entitlements` is still the main app subscription interface. If the decision gets reverted, we can just reintroduce that commit again.

**Comment by Isabe1le** [comment]
Please merge this 🙏🙏🙏

**Comment by Isabe1le** [comment]
🚀 LFG i’m a god

**Pull request merged**
