### PR TITLE
Deleted unused imports.

### PR DESCRIPTION
**Pull request by Victorsitou**
## Summary

I just hope I don't break something, thanks pylance!

## Checklist

- [ ] If code changes were made then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `black .`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by thesadru — APPROVED** [review]

**Review by shiftinv — APPROVED** [review]

**Comment by onerandomusername** [comment]
hi, consider using isort going forward. it should sort the imports, and is a nice compliment to black.

**Comment by Victorsitou** [comment]
> hi, consider using isort going forward. it should sort the imports, and is a nice compliment to black.

It sounds like a good idea, maybe I can make that change in this PR

**Comment by onerandomusername** [comment]
I think some of the unused imports are not necessary but might be used as part of the public api, so they might need to stay, but most of them looks good. I'll wait for a full review until after isort haha

**Comment by Victorsitou** [comment]
> I think some of the unused imports are not necessary but might be used as part of the public api, so they might need to stay, but most of them looks good. I'll wait for a full review until after isort haha


Ok so, I used `isort .` and almost all the library got changes haha
image

**Pull request merged**
