### PR TITLE
hope you like the centering

### PR DESCRIPTION
**Pull request by Cipher-GF**
## Summary

basically centered the text because it looked odd having the icons and banner centered and the rest not centered

## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by helish88** [comment]
huh 
изображение

**Comment by onerandomusername** [comment]
I would rather make the badges focused to the left than center everything.

**Comment by helish88** [comment]
and without message intent you can't run this command
image

**Comment by onerandomusername** [comment]
> 

that is irrelevant to this pull, and that is runnable and usable without message content intent.

**Comment by Cipher-GF** [comment]
> I would rather make the badges focused to the left than center everything.

your choice

**Comment by Cipher-GF** [comment]
> and without message intent you can't run this command image

fixed it

**Comment by onerandomusername** [comment]
I think it would be better to put the badges on the left, but I don't feel like any of these changes are necessary in the first place, but I am always open to suggestions to make it look better.

**Comment by ItsAleph** [comment]
Just my opinion, but it looks nice rn and no changes are needed.

**Comment by onerandomusername** [comment]
Yeah, I agree with that. I don't think these changes are necessary at this time.

**Pull request closed without merging**
