### PR TITLE
feet(:foot:): improve the subpar

### PR DESCRIPTION
**Pull request by EnokiUN**
## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `pdm lint`
    - [ ] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by EnokiUN** [comment]
I accidentally pressed enter while doing title emoji

**Review by ooliver1 — APPROVED** [review]

**Comment by Sharp-Eyes** [comment]
I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT I DON'T CONSENT

**Comment by ooliver1** [comment]
This truly improves the subpar :neckbeard:

**Comment by shiftinv** [comment]
This is truly one of the PRs of all time, thank you so much for the contribution.

Unfortunately, after thorough discussion with all maintainers, we've decided to decline your PR - it has left several files intact and, as such, isn't a suitable code style change.

**Comment by EnokiUN** [comment]
> This is truly one of the PRs of all time, thank you so much for the contribution.
> 
> Unfortunately, after thorough discussion with all maintainers, we've decided to decline your PR - it has left several files intact and, as such, isn't a suitable code style change.

what files, please give me another chance please I'll try to fix this

**Comment by Victorsitou** [comment]
lgtm

**Comment by elenakrittik** [comment]
i legitimately thought it's april first already after seeing this

**Pull request closed without merging**
