### PR TITLE
Added support for the `Color' class in embeds

### PR DESCRIPTION
**Pull request by Dellyis**

### CODE REVIEW

**Comment by thesadru** [comment]
`Color` is an alias of `Colour`. They are the exact same class under a different variable name.

**Comment by Dellyis** [comment]
Code
> embed = disnake.Embed(color=disnake.Color.blurple)

Error
> disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Expected disnake.Colour, int, or Embed.Empty but received method instead.

**Comment by thesadru** [comment]
It's `color=disnake.Color.blurple()`. You forgot to call the method.

**Comment by Dellyis** [comment]
Oops... I'm sorry

**Pull request closed without merging**
