### PR TITLE
Better style

### PR DESCRIPTION
**Pull request by LEv145**
## Summary

Улучшая стилизацию кода

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by thesadru** [comment]
I don't see how making variable names longer can be called a style improvement.

**Comment by LEv145** [comment]
So much more beautiful
The code passes flake8, mypy checks and follows (P)A/HC/LC + slightly corrected comments

**Comment by thesadru** [comment]
I'm fine with complying with flake8 & mypy but we won't be using longer variable or parameter names.

**Comment by LEv145** [comment]
Such code is more readable, and abbreviated variables look terrible

**Comment by LEv145** [comment]
Waiting for EQUENOS...

**Pull request merged**
