### PR TITLE
Replace favicon and banner.

### PR DESCRIPTION
**Pull request by abhigyantrips**
This PR changes the favicon for the docs, and the banner for the README.

### CODE REVIEW

**Comment by shiftinv** [comment]
The banner is taking up quite a lot of vertical space in the README, maybe just cut off the top/bottom(?).

**Comment by abhigyantrips** [comment]
Ah yes. This looks good?

nabber thin

**Review by jgayfer — APPROVED** [review]
Looks nice!

**Review by Victorsitou — APPROVED** [review]
It looks good!

**Pull request merged**
