### PR TITLE
Patch up some examples with views

### PR DESCRIPTION
**Pull request by CalebEevee**
## Summary

Add a _quit_ button in `paginator.py`. Fix issue in `disable_view.py`

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint` or `pre-commit run --all-files`
- [x] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by CalebEevee** [comment]
I'm not sure why one of the checks were not successful.

**Comment by CalebEevee** [comment]
Any suggestions?

**Comment by thesadru** [comment]
I highly doubt you actually ran `task lint` or `pre-commit run --all-files` since the checks would otherwise pass just fine.

**Comment by CalebEevee** [comment]
@thesadru do I need to change anything before merging?

**Comment by thesadru** [comment]
Run `task lint` or `pre-commit run --all-files`

**Comment by CalebEevee** [comment]
@thesadru I ran `pre-commit` and it still gave an error.

**Comment by CalebEevee** [comment]
image

**Review by thesadru — APPROVED** [review]

**Pull request merged**
