### PR TITLE
build(deps): update black to v23.9.1

### PR DESCRIPTION
**Pull request by onerandomusername**
## Summary

Bump black to 23.3.0 and enable their preview style which contains new fixes. Their stability policy has new changes released once a year, but a lot of these changes made the code much more readable.

This moves us closer to being able to enable E501 (if we want), as a multitude of these changes move long strings onto multiple lines.

## Checklist

- [ ] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pdm lint`
    - [x] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by shiftinv** [comment]
Overall this seems fine, I'll have a more detailed look tomorrow. I'm not really a huge fan of specific parts of string splitting - it's a bit *too* opinionated imo - but I know we don't get to pick and choose in the end.

Black doesn't "equally" split strings, i.e. such that the resulting lines are approximately equal in length, which looks rather weird:
```py
# input
"View is not persistent. Items need to have a custom_id set and View must have no timeout"

# current output
"View is not persistent. Items need to have a custom_id set and View must have no"
" timeout"
```
This can be fixed through manual review (black doesn't reformat literals that are already within line length limits), but it's not ideal.

The preview style still has a couple issues with multiline strings in specific contexts, however we seemingly haven't hit them (yet), to be fair. Another thing is visual misalignment of multiline f-strings, as outlined here: https://github.com/psf/black/issues/2915#issuecomment-1489950300

**Comment by shiftinv** [comment]
While some of these changes are neat, updating this PR from black v23.3.0 to v23.9.1 adds another ~1k lines of changes, some of which partially revert changes originally made by v23.3.0.
The preview style is unstable by nature (that's the entire point, after all), but I don't think this is sustainable for us... let's wait for a v24.x, maybe?

**Comment by shiftinv** [comment]
Changed the scope of this PR to only update black to 23.9.1 for now, which we need to be able to add `target-version = [..., "py312"]` in the future.
This now also uses mypyc-compiled black in pre-commit (which is supposedly ~2x faster), recently documented [here](https://black.readthedocs.io/en/stable/integrations/source_version_control.html).

**Comment by onerandomusername** [comment]
lgtm

**Pull request merged**
