### PR TITLE
feat(tests): define reveal_type at runtime

### PR DESCRIPTION
**Pull request by Snipy7374**
## Summary

- **Closes** GH-596

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by shiftinv** [comment]
This makes pyright completely ignore these `reveal_type`s; it appears that it only considers those defined in `typing`/`typing_extensions`, which makes sense:

image

image

(screenshots since github doesn't particularly like rendering a [24000-line file](https://github.com/microsoft/pyright/blob/21a5f136b4d4f1a98375b41fd25bac5ebf104c95/packages/pyright-internal/src/analyzer/typeEvaluator.ts))

I suppose one possible solution would be re-exporting `typing_extensions.reveal_type` in an `if TYPE_CHECKING:` block, but @onerandomusername might have something different in mind.

**Comment by Snipy7374** [comment]
[168fbd2](https://github.com/DisnakeDev/disnake/pull/875/commits/168fbd2890ad4aaedea46b308f87dfc3c0335020)

**Review by shiftinv — APPROVED** [review]
This looks good, thanks!

**Review by onerandomusername — APPROVED** [review]
lgtm

**Pull request merged**
