### PR TITLE
Add "USE_CLYDE_AI" permission

### PR DESCRIPTION
**Pull request by MCausc78**
## Summary
https://github.com/discord/discord-api-docs/pull/6354

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pdm lint`
    - [x] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by shiftinv — CHANGES_REQUESTED** [review]
thanks for the PR - a couple comments, mostly regarding documentation.

Additionally, since this implicitly gets denied when you can't send messages in a channel, it needs to be added in these two places as well:
https://github.com/DisnakeDev/disnake/blob/f08edf828d9700cab1c3386f5d358c61e67e65c7/disnake/abc.py#L639-L644
https://github.com/DisnakeDev/disnake/blob/f08edf828d9700cab1c3386f5d358c61e67e65c7/disnake/threads.py#L474-L479

**Review by shiftinv — APPROVED** [review]
lgtm!

**Comment by MCausc78** [comment]
https://github.com/discord/discord-api-docs/pull/6398

**Comment by spifory** [comment]
> [discord/discord-api-docs#6398](https://github.com/discord/discord-api-docs/pull/6398)

Please could you add this into a separate PR and not this one, just so there isn't any scope creep

**Comment by shiftinv** [comment]
Clyde was deactivated about a month ago (o7), so this is no longer needed.
thank you for the PR, nonetheless

**Pull request closed without merging**
